[Tests] add missing include
fix:

/src/hpp-fcl/test/collision.cpp:228:9: error: no template named 'vector' in namespace 'boost::mpl'; did you mean 'boost::container::vector'?
typedef boost::mpl::vector<OBB, RSS, KDOP<24>, KDOP<18>, KDOP<16>, kIOS, OBBRSS> BVs_t;
        ^~~~~~~~~~~~~~~~~~
        boost::container::vector
/usr/local/include/boost/container/container_fwd.hpp:104:7: note: 'boost::container::vector' declared here
class vector;
      ^
/src/hpp-fcl/test/collision.cpp:228:21: error: too many template arguments for class template 'vector'
typedef boost::mpl::vector<OBB, RSS, KDOP<24>, KDOP<18>, KDOP<16>, kIOS, OBBRSS> BVs_t;
                    ^                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/container/container_fwd.hpp:104:7: note: template is declared here
class vector;
      ^